### ISSUE TITLE
Found PW

### ISSUE THREAD

**Issue by str33tkid** [Pure-L0G1C/InstaBurst#9]
Hi its working for me, I found the password but how to bypass ---
"_We Detected An Unusual Login Attempt
To secure your account, we'll send you a security code to verify your identity_"

**Comment by Ethical-H4CK3R** [comment]
I’m not sure. I just write it, I don’t use it. Shouldn’t you be able to
receive the code as an sms or email?

**Comment by sami09snow** [comment]
what's the usr/pass?

**Comment by yeagley** [comment]
This is where using the app comes in, let it sit for a day or so 9/10 times the user will just click this was me as they don't want to change pass. Wait for this to happen then log in and seize it. #TrojanHorse

**Comment by Pure-L0G1C** [comment]
Highly unlikely, if I got an email saying someone logged into my account
from France, I’m not going to click that was me. And after that you’ll have
to login from a different location than the app, because the app uses a
proxies and hides your location, and so, the user will get the message
again, which they will then change their credentials. The app can’t use the
same proxy after a day or so because proxies go bad after a few hours.

**Comment by yeagley** [comment]
I am telling you from personal experience man. It does not happen, I know it sounds surprising but for me most large accounts (non personal niche accounts) are using rounds bots, third party apps, powerlike/autolike bots, follow/unfollow, etc. which all generate "Was This You?" on a fairly routine basis. Currently running 6 accounts from 25-450k and they are all getting the was this you 2-3 times weekly and I am always authorize it because if I do not it will stop the bots. I have only "acquired" 2 accounts and this method worked both times. Most accounts worth using your creation on will probably be used to clicking This Was Me. I am not an expert by any means though, just have a couple years of experience on the user side of the house.

**Comment by Pure-L0G1C** [comment]
So, what ideas are you trying to propose?
